flipped-aurora/gin-vue-admin

- QMPlusServer/init/qmlog/qmlog.go
- QMPlusServer/tools/directory.go
when i clone code to local, run it directly, and an error will be reported that there is no log in this folder.
> Add check for log directory.

- QMPlusServer/config/config.go
- QMPlusServer/init/qmsql/initMysql.go
- QMPlusServer/static/config/config.json
> mysql 加打开日志打印模式

- QMPlusServer/controller/api/exa_customer.go
- QMPlusServer/controller/api/sys_api.go
- QMPlusServer/controller/api/sys_casbin.go
- QMPlusServer/controller/api/sys_menu.go
- QMPlusServer/db/qmplus.sql
- QMPlusServer/docs/docs.go
- QMPlusServer/docs/swagger.json
- QMPlusServer/docs/swagger.yaml
- QMPlusServer/model/dbModel/exa_customer.go
- QMPlusServer/model/sysModel/sys_api.go
- QMPlusServer/model/sysModel/sys_base_menu.go
- QMPlusServer/model/sysModel/sys_casbin.go
- QMPlusServer/router/exp_customer.go
- QMPlusServer/router/sys_api.go
- QMPlusServer/router/sys_casbin.go
- QMPlusServer/router/sys_menu.go
- QMPlusVuePage/src/api/api.js
- QMPlusVuePage/src/api/casbin.js
- QMPlusVuePage/src/api/customer.js
- QMPlusVuePage/src/api/menu.js
- QMPlusVuePage/src/view/example/customer/customer.vue
- QMPlusVuePage/src/view/superAdmin/api/api.vue
- QMPlusVuePage/src/view/superAdmin/authority/components/apis.vue
- QMPlusVuePage/src/view/superAdmin/menu/menu.vue
updata->update,Updata->Update
为了以后国际友人不嘲笑我们
> updata->update,Updata->Update

- QMPlusVuePage/src/view/login/login.vue
> 登录失败后刷新验证码

- README.md
Spelling fix: ever->server, urtils->utils
> Spelling fix: erver->server, urtils->utils

- README-zh_CN.md
- README.md
> Gin vue admin v2 dev

- README-zh_CN.md
- README.md
> nick name mixed: krank666 granty1

- .gitignore
- server/config.yaml
- server/middleware/casbin_rcba.go
> add /web/dist to .gitignore

- README-zh_CN.md
- README.md
README-zh_CN.md: add Contributing Guide.
> README.md: add Contributing Guide.

- web/src/view/systemTools/autoCode/index.vue
代码生成器页面添加field列表添加上移和下移的功能，已方便调整字段顺序
> field列表添加上移和下移的功能

- server/resource/template/te/api.go.tpl
- server/resource/template/te/model.go.tpl
- server/resource/template/te/router.go.tpl
- server/resource/template/te/service.go.tpl
- server/service/sys_auto_code.go
- server/utils/directory.go
如[issue97](https://github.com/flipped-aurora/gin-vue-admin/issues/97)所述
重构`CreateTemp`  
修改`tpl`文件，使其满足`go fmt`
> 重构CreateTemp

- server/api/v1/sys_auto_code.go
- server/core/server.go
- server/go.mod
- server/initialize/plug.go
- server/model/exa_customer.go
- server/model/exa_file_upload_download.go
- server/model/sys_api.go
- server/model/sys_authority.go
- server/model/sys_authority_menu.go
- server/model/sys_auto_code.go
- server/model/sys_base_menu.go
- server/model/sys_jwt_blacklist.go
- server/model/sys_user.go
- server/model/sys_workflow.go
- server/model/sys_workflow_process.go
- server/resource/template/fe/table.vue.tpl
- server/resource/template/te/api.go.tpl
- server/resource/template/te/model.go.tpl
- server/resource/template/te/request.go.tpl
- server/resource/template/te/service.go.tpl
- server/service/sys_user.go
- web/src/view/layout/screenfull/index.vue
- web/src/view/superAdmin/authority/authority.vue
- web/src/view/systemTools/autoCode/component/fieldDialog.vue
- web/src/view/systemTools/autoCode/index.vue
修复点击全屏后，按Esc键退出全屏，全屏按钮图标没有改变的问题
> fix fullscreen bug

- server/resource/template/fe/table.vue.tpl
- server/resource/template/te/model.go.tpl
- server/resource/template/te/service.go.tpl
wrong src file: "\server\resource\template\te\service.go.tpl"
> 修复优化自动代码中对bool类型搜索字段的支持

- server/resource/template/fe/table.vue.tpl
- server/resource/template/te/model.go.tpl
- server/resource/template/te/service.go.tpl
fix : AutoCode table can not show bool field
> 修复:AutoCode生成的表格不显示bool值

- server/go.mod
- server/utils/upload.go
> fix qiniu go mod bug

- server/core/server.go
- server/core/server_other.go
- server/core/server_win.go
- server/go.mod
移除对 captcha 的引用
非 Windows 操作系统使用endless启动服务
> 非 Windows 操作系统使用endless启动服务

- server/api/v1/sys_email.go
- server/config.yaml
- server/config/config.go
- server/go.mod
- server/initialize/router.go
- server/router/sys_email.go
- server/service/sys_email.go
- server/utils/email.go
- web/src/api/email.js
- web/src/view/systemTools/system/system.vue
> add email module

- server/config.yaml
- server/config/gorm.go
- server/core/server.go
- server/initialize/gorm.go
- server/initialize/logger.go
- server/initialize/router.go
- server/middleware/operation.go
- server/router/exp_customer.go
- server/router/sys_api.go
- server/router/sys_authority.go
- server/router/sys_casbin.go
- server/router/sys_dictionary.go
- server/router/sys_dictionary_detail.go
- server/router/sys_email.go
- server/router/sys_jwt.go
- server/router/sys_menu.go
- server/router/sys_operation_record.go
- server/router/sys_system.go
- server/router/sys_user.go
- server/router/sys_workflow.go
- server/service/sys_auto_code.go
- web/src/main.js
- 新增文件：
- server/initialize/logger.go
- 修改文件：
- server/initialize/gorm.go
- server/config/gorm.go
- server/config.yaml
- 功能实现：
- gorm日志打印入库
- 实现功能说明：
- 自定义gorm的logger所需要的接口，使用全局zap自定义打印规则,实现日志可以通过zap记录入本地log文件里
- 注意事项
- `config.yaml` 中 `mysql`下的 `log-zap` 优先于 `log-mod`
> gorm日志收集进log功能

- web/public/index.html
- web/vue.config.js
使用cdn资源还有优化空间：
element-ui目前是打包后最大的，但还没有思路如何使用cdn
> 前端发布优化，部分组件使用cdn资源，不打包

- web/src/components/upload/image.vue
修复提示权限不足和图片显示问题
文件：web/src/components/upload/image.vue
> 修复提示权限不足和图片显示问题

- server/utils/cmd_Task.go
> 修改了热更正在运行时重启信号的丢弃

- web/build.config.js
- web/public/index.html
- web/vue.config.js
>  chore: 增加自动扫描package.json, 从cdn引入资源

- server/api/v1/sys_api.go
- server/api/v1/sys_operation_record.go
- server/model/request/common.go
- server/model/request/sys_operation_record.go
- server/resource/template/server/api.go.tpl
- server/resource/template/server/model.go.tpl
- server/resource/template/server/request.go.tpl
- server/resource/template/server/service.go.tpl
- server/resource/template/web/workflowForm.vue.tpl
修复了swag文档自动化生成失败的bug；完善了自动生成代码的swag部分
> 修复了swag文档自动化生成失败的bug；完善了自动生成代码的swag部分

- server/api/v1/sys_api.go
- server/api/v1/sys_operation_record.go
- server/model/request/common.go
- server/model/request/sys_operation_record.go
- server/resource/template/server/api.go.tpl
- server/resource/template/server/model.go.tpl
- server/resource/template/server/request.go.tpl
- server/resource/template/server/service.go.tpl
- server/resource/template/web/workflowForm.vue.tpl
Reverts flipped-aurora/gin-vue-admin#338
> Revert "修复了swag文档自动化生成失败的bug；完善了自动生成代码的swag部分"

- server/api/v1/sys_auto_code.go
- server/router/sys_auto_code.go
- server/service/sys_auto_code.go
新增代码生成预览接口
- 修改 server/api/v1/sys_auto_code.go
- 修改 server/router/sys_auto_code.go
- 修改 server/service/sys_auto_code.go
> Gva gormv2 dev

- web/src/router/index.js
NavigationDuplicated: Avoided redundant navigation to current location
> NavigationDuplicated error

- server/api/v1/sys_system.go
- server/router/sys_system.go
修改
- server/api/v1/sys_system.go
- server/router/sys_system.go
> 新增api 重启服务（非windows）

- server/api/v1/sys_initdb.go
- server/api/v1/sys_system.go
- server/cmd/gva/initdb.go
- server/cmd/information/system/data_authorities.go
- server/cmd/information/system/workflow.go
- server/initialize/gorm.go
- server/initialize/router.go
- server/main.go
- server/middleware/init.go
- server/model/request/sys_init.go
- server/model/sys_init.go
- server/service/sys_initdb.go
- server/utils/init_db.go
- server/utils/mysql.go
修改gva initdb 判断是否已经创建的一些小问题
新增api生成数据库并初始化回写配置
修改文件：
server/cmd/gva/initdb.go
server/cmd/information/data_authorities.go
server/cmd/information/workflow.go
server/initialize/gorm
server/main.go
新增文件：
server/api/v1/sys.initdb.go
server/middleware/init.go
server/model/sys_init.go
server/service/sys_initdb.go
servcer/utils/init_db.go
迁移文件
server/cmd/gva/mysql.go->server/utils/mysql.go
> 新增功能-api生成数据库并初始化回写配置

- server/config.yaml
- server/config/auto_code.go
- server/config/config.go
- server/core/viper.go
- server/service/sys_auto_code.go
修改
- server/config.yaml
- server/config/config.go
- server/config/viper.go
- server/service/sys_auto_code.go
新增
- server/config/auto_code.go
> 代码自动迁移动态适配

- server/model/sys_auto_code.go
- server/service/sys_auto_code.go
- server/utils/file_operations.go
- 修改
server/model/sys_auto_code.go
server/service/sys_auto_code.go
server/utils/file_operations.go
> #409 bug修复

- README.md
- dockerfile_server
修复虚拟机里面docker-compose up失败的问题，失败原因见下图，
> fix:fail to start with docker-compose

- server/api/v1/sys_system.go
- server/config.yaml
- server/config/auto_code.go
- server/service/sys_auto_code.go
- server/utils/reload.go
修改
- server/api/v1/sys_system.go
- server/config.yaml
- server/config/auto_code.go
- server/service/sys_auto_code.go
新增
- server/utils/reload.go
> 新增自动迁移创建路由后重启

- server/service/sys_casbin.go
> service/sys_casbin.go: fix casbin runs slowly

- server/service/sys_casbin.go
修改
- server/service/sys_casbin.go
> fix casbin datarace

- server/service/sys_casbin.go
Reverts flipped-aurora/gin-vue-admin#482
> Revert "Gva gormv2 dev"

- server/config.yaml
- server/core/server.go
- server/service/sys_casbin.go
- web/src/main.js
> 修复casbin map占用问题

- server/main.go
> 增加 go generate 懒人模式

- web/src/view/systemTools/autoCode/component/previewCodeDialg.vue
> 依照eslint格式化

- server/config.yaml
- server/config/config.go
- server/config/gorm.go
- server/initialize/gorm.go
- server/model/request/sys_init.go
- server/service/sys_initdb.go
- server/source/authority_menu.go
- web/src/view/init/init.vue
- web/src/view/systemTools/autoCode/component/previewCodeDialg.vue
> Revert "增加sqlite数据库的初始化"

- server/service/exa_excel_parse.go
> exa_excel_parse.go: fix return err

- server/api/v1/sys_initdb.go
- server/service/sys_initdb.go
创建失败不更改config文件保持,前端保持在init界面
修改文件
- server/api/sys_initdb.go
- server/service/sys_initdb.go
> perf:优化初始化流程

- server/utils/upload/aliyun_oss.go
- server/utils/upload/qiniu.go
- server/utils/upload/tencent_cos.go
I found those type of fileserver don't close file.
> aliyun_oss,qiniu,tencent_cos:  fix file open close

- server/resource/template/web/api.js.tpl
- server/resource/template/web/form.vue.tpl
- server/resource/template/web/table.vue.tpl
> 前端模板eslit修改

- web/build.config.js
- web/src/core/config.js
- web/src/core/gin-vue-admin.js
> modified 统一代码风格

- server/api/v1/sys_authority.go
- server/model/request/sys_casbin.go
- server/model/request/sys_menu.go
修改了:
- server/api/v1/sys_authority.go
- server/model/request/sys_casbin.go
- server/model/request/sys_menu.go
> fix:创建用户初始化权限,确保用户可用

- server/service/sys_initdb.go
> 修复特殊符号下初始化数据库时报错的bug

- README-en.md
- README.md
更新文件：
- README.md
- README-en.md
更新说明：
- 更新中英文READNE文档
> update: README.md and README-en.md

- server/resource/template/server/api.go.tpl
- server/resource/template/server/model.go.tpl
- server/resource/template/server/router.go.tpl
- server/resource/template/server/service.go.tpl
修改模板中的注释格式为官方推荐的格式.
官方手册地址:
https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences
> 修改模板中的注释格式为官方推荐的格式

- server/README.md
[a6e62f388eb9e15e063ac91e49e61ad474eec71a](https://github.com/flipped-aurora/gin-vue-admin/commit/a6e62f388eb9e15e063ac91e49e61ad474eec71a)
更新文件
- server/README.md
更新说明
- 完善server的README.md 说明文档
> update: server/README.md

- server/config/gorm.go
- server/initialize/gorm.go
- server/initialize/internal/logger.go
- server/initialize/timer.go
[ff1f61bf694b9d3aa2ed0156758f85209683ca5a](https://github.com/flipped-aurora/gin-vue-admin/pull/569/commits/ff1f61bf694b9d3aa2ed0156758f85209683ca5a)
修改文件
- server/config/gorm.go
- server/initialize/gorm.go
- server/initialize/internal/logger.go
- server/initialize/timer.go
- 删除多余调试打印语句
实现功能
- 不使用zap进行写日志，使用默认的gorm的logger
```yaml
mysql:
path: 127.0.0.1:13307
config: charset=utf8mb4&parseTime=True&loc=Local
db-name: gva
username: root
password: gdkid,,..
max-idle-conns: 0
max-open-conns: 0
log-mode: "info"
log-zap: false
```
- 使用zap进行写日志
```yaml
mysql:
path: 127.0.0.1:13307
config: charset=utf8mb4&parseTime=True&loc=Local
db-name: gva
username: root
password: gdkid,,..
max-idle-conns: 0
max-open-conns: 0
log-mode: "info"
log-zap: true
```
> update: 自定义gorm的logger优化

- web/src/view/systemTools/autoCode/index.vue
> 自动化代码可选项优化

- web/Dockerfile
update file
- web/Dockerfile
fixed:
- cnpm install error
> fix: web/Dockerfile cnpm install error

- server/model/sys_autocode_history.go
- server/source/api.go
- server/source/casbin.go
- server/source/menu.go
- web/src/api/autoCode.js
- web/src/view/systemTools/autoCodeAdmin/index.vue
> 增加自动化代码回滚功能

- server/config.yaml
- web/src/style/base.scss
> 修复分页器左侧border消失的bug

- server/core/server.go
- web/src/core/gin-vue-admin.js
> 正式发布V2.4.4版本

- server/api/v1/system/sys_user.go
- server/docs/docs.go
- server/docs/swagger.json
- server/docs/swagger.yaml
Update the changePassword API swagger method
> Update changePassword swagger method

- server/resource/template/server/service.go.tpl
[service.go.tpl] Fix typo in time.Time FieldType.
> [service.go.tpl] Fix typo in time.Time FieldType. 

- server/model/system/sys_user.go
model/system/sys_user.go comment 错误
> update: model/system/sys_user.go comment 错误

- web/src/mixins/infoList.js
- web/src/view/example/upload/upload.vue
> 修复本地模式下的文件下载问题

- web/src/permission.js
- web/src/store/module/user.js
> 修复在登录状态下访问白名单路由导致白屏的bug

- server/Dockerfile
> fixed: #699 go build 报错 gcc问题

- web/src/view/routerHolder.vue
https://github.com/flipped-aurora/gin-vue-admin/issues/698
解决白屏问题
> 解决使用自动二级路由导致的切换tab白屏问题

- web/src/view/dashboard/dashbordCharts/echartsLine.vue
- web/src/view/dashboard/dashbordTable/dashbordTable.vue
- web/src/view/layout/index.vue
> 调整不同屏幕下的兼容性

- web/src/style/element_visiable.scss
- web/src/view/systemTools/autoCode/index.vue
> 修复预览自动化代码全选和复制的bug

- web/src/view/dashboard/dashbordCharts/echartsLine.vue
- web/src/view/layout/aside/historyComponent/history.vue
- web/src/view/layout/aside/index.vue
- web/src/view/layout/screenfull/index.vue
- web/src/view/system/state.vue
优化将beforeDestroy更改为beforeUnmount
> 修正生命周期钩子，将`beforeDestroy`更改为`beforeUnmount` (#738)

- web/src/view/systemTools/formCreate/index.vue
> [Feature]:#753

- web/src/view/systemTools/autoCode/component/fieldDialog.vue
> fix:798:数据库列表候选丢失

- web/limit.js
- web/package-lock.json
- web/package.json
> 增加内存不足时使用的命令

- server/source/system/api.go
> fixed: source/system/api 数据错误

- server/config.docker.yaml
- server/config.yaml
> fixed: 系统配置中OSS类型字段的注释错误;

- .github/workflows/devops.yml
- server/config.docker.yaml
修改docker配置文件中mysql连接方式，增加自动构建tag
> 修改docker配置文件中mysql连接方式，增加自动构建tag

- server/api/v1/example/exa_breakpoint_continue.go
- server/core/server.go
- server/resource/template/web/form.vue.tpl
- server/resource/template/web/table.vue.tpl
- server/service/example/exa_breakpoint_continue.go
- server/source/system/api.go
- server/source/system/casbin.go
- web/package.json
- web/src/api/breakpoint.js
- web/src/components/upload/image.vue
- web/src/core/config.js
- web/src/core/gin-vue-admin.js
- web/src/core/global.js
- web/src/utils/request.js
- web/src/view/about/index.vue
- web/src/view/example/breakpoint/breakpoint.vue
- web/src/view/example/customer/customer.vue
- web/src/view/example/upload/upload.vue
- web/src/view/superAdmin/api/api.vue
- web/src/view/superAdmin/dictionary/sysDictionary.vue
- web/src/view/superAdmin/dictionary/sysDictionaryDetail.vue
- web/src/view/superAdmin/operation/sysOperationRecord.vue
- web/src/view/superAdmin/user/user.vue
> Gva vue3 setup

- server/config.yaml
- server/config/config.go
- server/config/oss_aws.go
- server/go.mod
- server/go.sum
- server/utils/upload/aws_s3.go
- server/utils/upload/upload.go
添加了一个AWS S3的图床，使用`示例文件 -> 媒体库 -> 普通上传` 功能测试如下。
PS：仓库里没有 develop 分支，因此只能合并到 main 分支
> 添加AWS S3上传功能

- .github/workflows/build_test.yml
- .github/workflows/devops.yml
新的测试用例更新，新增了数据库初始化接口，获取菜单接口，获取用户权限接口测试
> new test-build1.0

- server/Dockerfile
- web/Dockerfile
dockerfile优化：减小镜像大小 ，更改node版本为16，同时npm更换为yarn
> dockerfile优化：减小镜像大小 ，更改node版本为16，同时npm更换为yarn 

- web/src/utils/btnAuth.js
- web/src/view/systemTools/system/system.vue
> 增加前端控制台开启redis

- README-en.md
- README.md
update readme: update gin badge to 1.7.0
> update readme: update gin badge to 1.7.0

- README-en.md
- README.md
> update badge for readme.en

- README-en.md
- README.md
- server/middleware/operation.go
- server/model/common/request/common.go
- server/service/system/sys_api.go
- server/service/system/sys_base_menu.go
- server/service/system/sys_user.go
- web/src/pinia/modules/user.js
> fixed:调整v2.5.0测试版bug

- server/config.yaml
- server/config/oss_aws.go
- server/utils/upload/aws_s3.go
可行性参考官方文档https://docs.min.io/docs/how-to-use-aws-sdk-for-go-with-minio-server.html
已测试可行
> AwsS3新增配置属性,可以兼容minio

- server/service/system/sys_initdb.go
- server/service/system/sys_initdb_mysql.go
spelling corrected: initMsqlDB -->initMysqlDB
> spelling corrected: initMsqlDB -->initMysqlDB

- web/src/permission.js
> JSON.stringify出现循环引用错误

- README.md
> chore: update docs of go-zero

- server/service/system/sys_dictionary.go
> 修复当字典没有详情列表时,删除字典提示失败的问题

- server/model/system/sys_user.go
> sys_user.go 注释错误

- web/src/utils/request.js
> 增加请求发生异常的判断

- server/api/v1/example/exa_file_upload_download.go
- server/model/common/request/common.go
- server/router/example/exa_file_upload_and_download.go
- server/service/example/exa_file_upload_download.go
- web/src/api/fileUploadAndDownload.js
- web/src/components/chooseImg/index.vue
- web/src/components/upload/common.vue
- web/src/style/base.scss
- web/src/view/example/upload/upload.vue
媒体库：
1、文件名更改为：文件名/备注；
2、媒体库增加搜索，弹出的选择媒体库增加分页；
3、媒体库文件名/备注增加点击可编辑（弹出的选择媒体库同样增加）；
4、媒体库缩略图居中，不压缩或者拉伸
> Develop媒体库： 1、文件名更改为：文件名/备注； 2、媒体库增加搜索，弹出的选择媒体库增加分页； 3、媒体库文件名/备注增加点击可编辑（弹出的选择媒体库同样增加）； 4、媒体库缩略图居中，不压缩或者拉伸

- server/api/v1/system/sys_authority_btn.go
/authorityBtn/getAuthorityBtn -> /authorityBtn/setAuthorityBtn
> fix swagger comment route typo

- server/middleware/cors.go
> cors.go fix 角色切换bug

- web/src/view/superAdmin/dictionary/sysDictionaryDetail.vue
> 修改多个字典管理标签切换

- web/package.json
- web/src/view/dashboard/dashboardCharts/echartsLine.vue
> update: update echarts version to 5.x

- docker-compose-dev.yaml
> 优化docker-compose，默认去除淘宝源

- server/service/system/sys_menu.go
这是感觉是重复写了 Preload("Parameters") 冗余了
> remove multi preload

- docker-compose-dev.yaml
- web/.env.development
> 修复docker中代码生成问题

- web/src/view/layout/aside/historyComponent/history.vue
> 解决historyComponent无法删除问题

- README.md
- gin-vue-admin.code-workspace
Use `code gin-vue-admin.code-workspace` open all projects.
Launch `Both (Backend & Frontend)`
> feat: use workspace & add launch config

- server/source/system/authorities_menus.go
- server/source/system/casbin.go
- web/src/permission.js
- web/src/pinia/modules/user.js
- fix(server): casbin DataInserted v1 v2 的参数反了
- fix(server): authoritiesMenus DataInserted 的检查没有效果
> fix(web): 修复被删除的用户的 token 发生无限循环

- server/api/v1/system/sys_auto_code.go
- server/config.yaml
- server/config/timer.go
- server/initialize/timer.go
- server/model/system/sys_auto_code.go
- server/service/system/sys_auto_code.go
- server/utils/timer/timed_task.go
> 自动插件模式鉴定调整

- server/api/v1/system/sys_auto_code.go
- server/config.yaml
- server/config/timer.go
- server/initialize/timer.go
- server/model/system/sys_auto_code.go
- server/service/system/sys_auto_code.go
- server/utils/timer/timed_task.go
- web/src/view/systemTools/installPlugin/index.vue
> fix: #1160 

- web/package.json
- web/src/style/base.scss
- web/src/style/button.scss
- web/src/view/superAdmin/authority/authority.vue
- web/src/view/superAdmin/authority/components/apis.vue
- web/src/view/superAdmin/authority/components/datas.vue
- web/src/view/superAdmin/authority/components/menus.vue
> 前端性能优化，体验优化

- web/src/api/breakpoint.js
- web/vite.config.js
> 修复build失败的问题

- web/src/api/breakpoint.js
- web/src/pinia/modules/user.js
- web/src/view/login/index.vue
- web/vite.config.js
登录页面去掉默认用户名和密码，就会看到此属性的效果；
以下是element-plus对此属性的解释
属性 | 说明 | 类型 | 默认值
-- | -- | -- | --
validate-on-rule-change | 是否在 rules 属性改变后立即触发一次验证 | boolean | true
> 避免页面加载后立即触发一次验证，页面出现一片红色的警告的情况

- server/service/example/exa_breakpoint_continue.go
> 优化，合并update方法

- server/config.yaml
- server/config/jwt.go
- server/core/viper.go
- server/initialize/outer.go
- server/main.go
- server/middleware/jwt.go
- server/model/system/request/jwt.go
- server/service/system/jwt_black_list.go
- server/utils/human_duration.go
- server/utils/jwt.go
整理配置文件，jwt过期时间和缓冲时间支持1d2h3m4s事件类型
> 整理配置文件，jwt过期时间和缓冲时间支持1d2h3m4s事件类型

- server/model/system/sys_user.go
sys_user 表缺少索引，SQL慢查询。导致登录时间太长。 增加索引解决问题
> fix: 增加索引解决登录太慢的问题

- server/config.yaml
- server/model/system/sys_auto_code.go
- server/model/system/sys_user.go
- server/resource/autocode_template/server/api.go.tpl
- server/resource/autocode_template/server/model.go.tpl
- server/resource/autocode_template/server/service.go.tpl
- server/utils/validator.go
- web/.env.development
- web/src/main.js
- web/src/utils/positionToCode.js
- web/src/view/dashboard/dashboardTable/dashboardTable.vue
- web/src/view/systemTools/autoCode/index.vue
- web/vite.config.js
- web/vite_plugin/code-server/index.js
- web/vite_plugin/gva-position/index.js
增加shift+鼠标左键定位代码功能，增加自动创建资源权限标识功能，细节调优。
> 增加shift+鼠标左键定位代码功能，增加自动创建资源权限标识功能，细节调优。

- server/api/v1/example/exa_breakpoint_continue.go
- server/api/v1/example/exa_customer.go
- server/api/v1/example/exa_excel.go
- server/api/v1/example/exa_file_upload_download.go
- server/api/v1/system/sys_api.go
- server/api/v1/system/sys_authority.go
- server/api/v1/system/sys_authority_btn.go
- server/api/v1/system/sys_auto_code.go
- server/api/v1/system/sys_auto_code_history.go
- server/api/v1/system/sys_captcha.go
- server/api/v1/system/sys_casbin.go
- server/api/v1/system/sys_dictionary.go
- server/api/v1/system/sys_dictionary_detail.go
- server/api/v1/system/sys_initdb.go
- server/api/v1/system/sys_jwt_blacklist.go
- server/api/v1/system/sys_menu.go
- server/api/v1/system/sys_operation_record.go
- server/api/v1/system/sys_system.go
- server/api/v1/system/sys_user.go
- server/docs/docs.go
- server/docs/swagger.json
- server/docs/swagger.yaml
- server/main.go
- server/plugin/email/api/sys_email.go
- server/resource/autocode_template/server/api.go.tpl
- server/utils/validator.go
Update:
- swagger docs
- api层错误处理以及代码格式统一化
- swagger docs fmt格式化
> Fixed: c.ShouldBindXXX 未错误处理 #1224

- web/src/view/systemTools/system/system.vue
> 修改前端日志配置页面对应key

- deploy/docker-compose/docker-compose-dev.yaml
- deploy/docker-compose/docker-compose.yaml
- server/config.docker.yaml
解决部分数据库 root 用户默认只能 localhost 连接问题
> fix: 数据库默认用户设置为普通用户 gva ，同时解决初始化后提示授权失效问题

- server/resource/autocode_template/server/api.go.tpl
- server/resource/autocode_template/server/service.go.tpl
> 修改自动化代码不携带资源标识的created_by错误

- web/src/pinia/modules/router.js
- web/src/view/superAdmin/menu/menu.vue
https://github.com/flipped-aurora/gin-vue-admin/issues/1257
> feat:add base router setting

- server/middleware/logger.go
fix `AuthProcess` function runtime error: invalid memory address or nil pointer dereference
> logger.go: fix nil pointer dereference

- web/src/locales/ar.json
- web/src/locales/en.json
- web/src/locales/zh.json
- web/src/view/superAdmin/user/user.vue
- web/src/view/systemTools/autoCode/component/previewCodeDialg.vue
- web/src/view/systemTools/autoCode/index.vue
1. 代碼生成器畫面無法讀取
2. 使用數據庫創建代碼功能無法自動填入資料欄位
3. 編輯用戶出現密碼不可為空
> fixbug: （i18n版本）

- web/src/view/superAdmin/user/user.vue
> [user.vue]: 新增邮箱手机合法性校验，邮箱手机非必填

- server/config.yaml
- server/config/system.go
- server/initialize/plugin.go
- server/initialize/router.go
- server/middleware/casbin_rbac.go
- web/src/view/systemTools/system/system.vue
https://github.com/flipped-aurora/gin-vue-admin/issues/1332
> feat:backend add router global prefix

- web/src/permission.js
- web/src/pinia/modules/router.js
> fixed:#1336

- web/src/main.js
https://github.com/flipped-aurora/gin-vue-admin/issues/1350
> 补充按需加载遗漏的指令加载方式的css

- server/utils/upload/obs.go
uploadFile返回值顺序为：filePath,fileName,error
但当前部分return返回值里fileName放在第一个上。
file.Open()后，缺少Close()
> 华为obs，file.Open后缺少close，uploadFile返回值顺序不对

- server/middleware/jwt.go
err == utils.TokenExpired 修改为 errors.Is(err, utils.TokenExpired)
> fixed: middleware jwt 

- server/config.yaml
- server/config/db_list.go
- server/model/system/request/sys_init.go
Reverts flipped-aurora/gin-vue-admin#1388
> Revert "[feat]: config for TLS connection in init MySQL"

- server/go.mod
- server/go.sum
- server/service/system/sys_casbin.go
Reverts flipped-aurora/gin-vue-admin#1395
> Revert "fix: 修复并发请求API情况下的读写冲突问题"

- web/src/pinia/modules/router.js
- web/src/view/layout/search/search.vue
> 菜单项如果有参数则携带参数跳转

- server/service/system/sys_api.go
> fixed:#1416

- web/package.json
> package.json: fix dependency conflict

- web/jsconfig.json
fix:修复web在vscode打开的时候识别不了@符号的bug
> fix:修复web在vscode打开的时候识别不了@符号的bug

- server/initialize/internal/gorm.go
> feat:解决mysql配置日志等级不生效问题

- server/utils/upload/aliyun_oss.go
- server/utils/upload/aws_s3.go
- server/utils/upload/local.go
- server/utils/upload/qiniu.go
- server/utils/upload/tencent_cos.go
Fix typo 'Field' to 'failed' #1460
> FIX: globally fix typo 'Field' to 'failed'

- server/config/gorm_sqlite.go
Make sqlite path compatible with linux environment.
> use filepath join instead of hardcode separator

- server/service/system/sys_auto_code.go
> feat: use description to name apiGroup

- README-en.md
- README.md
> README gin版本标记错误

- server/resource/autocode_template/web/table.vue.tpl
- web/src/utils/format.js
> 生成代码模版文件新增了查看详情、详情内图片预览、文件下载

- server/model/system/request/sys_init.go
修复不同系统环境下创建db文件路径错误的问题，根据当前系统环境匹配对应的目录分隔符
> fix:修复不同系统环境下创建db文件路径错误的问题

- server/config/auto_code.go
- server/config/config.go
- server/config/db_list.go
- server/config/email.go
- server/config/oss_aws.go
- server/config/oss_qiniu.go
- server/config/redis.go
- server/config/system.go
- server/config/timer.go
依赖gopls的分析，quick fix（这一步会把注释丢了），然后参考原代码补充注释
> 优化config字段排列，使得内存对齐

- server/resource/autocode_template/server/model.go.tpl
resource/autocode_template/server/model.go.tpl: 生成字段注释，使得swag init 能提取到model字段的中文名字
> resource/autocode_template/server/model.go.tpl: swag文档添加中文信息

- web/src/components/selectFile/selectFile.vue
> 调整了文件上传无法异步赋值的bug

- server/service/system/sys_casbin.go
issues地址：
https://github.com/flipped-aurora/gin-vue-admin/issues/1533
> 解决bug：为角色添加权限时，如果有重复api权限，该角色所有权限均添加失败（包括登录）

- web/package.json
- web/src/components/office/docx.vue
- web/src/components/office/excel.vue
- web/src/components/office/index.vue
- web/src/components/office/pdf.vue
- web/src/components/selectFile/selectFile.vue
> 初步构建了文件预览组件

- server/config.yaml
- server/initialize/router.go
- server/middleware/operation.go
- server/utils/captcha/redis.go
- web/src/components/richtext/rich-edit.vue
- web/src/components/richtext/rich-view.vue
> 修复富文本bug，调整日志输出，修复已知bug

- web/src/view/systemTools/system/system.vue
>  web/src/view/systemTools/system/system.vue : fix 图形验证码配置 bug

- server/api/v1/system/sys_api.go
- server/api/v1/system/sys_authority.go
- server/service/system/sys_api.go
- server/service/system/sys_authority.go
- server/service/system/sys_casbin.go
- server/service/system/sys_user.go
> [feature]:调整角色的创建，删除操作为事务模式

- server/api/v1/system/sys_captcha.go
- server/global/model.go
项目中实际请求的参数为ID,swagger里面为id的bug；验证码防爆bug
> 修复swagger请求的id问题；验证码防爆问题

- server/initialize/mongo.go
修复mongodb index默认name太长而导致创建索引失败, 在组装keys数据进行排序以便符合bson.M的构造
> Update: MongoDb Index Name Too Long

- server/api/v1/system/sys_auto_code.go
> sys_auto_code fix: log文字提示错误

- web/src/components/office/index.vue
- web/src/components/selectImage/selectImage.vue
上传一张jpeg格式的图片，提示“当前类型不支持使用”
变更 jpge -> jpeg
> TYPO: 图片格式jpeg

- web/src/view/superAdmin/user/user.vue
branch: i18n-dev-new
1.修复添加管理员时，用户名字段验证规则未生效
2.修复编辑用户后，点击添加用户,仍然是编辑用户的问题
> 修复分支i18n-dev-new，用户管理页面

- server/config/zap.go
> zapcore.WarnLevel修改成zapcore.ErrorLevel

- web/src/view/systemTools/autoCode/index.vue
> feat: 将placeholder替换为tooltip

- server/config/config.go
- server/service/system/sys_menu.go
- server/service/system/sys_user.go
> 修复#1611提及的反引号导致pgsql搜索不支持的bug

- web/src/view/systemTools/autoCode/index.vue
> 修复代码生成器 列表中数据库字段描述回显错误

- server/api/v1/system/sys_auto_code.go
- server/service/system/sys_auto_code.go
解决打包插件解压报错的问题
https://github.com/flipped-aurora/gin-vue-admin/issues/1628
> 解决打包插件解压报错的问题

- server/config.yaml
- server/config/mongo.go
- server/initialize/mongo.go
> mongo use auth-source

- server/model/system/response/sys_auto_code.go
- server/model/system/sys_auto_code.go
- server/resource/autocode_template/server/api.go.tpl
- server/resource/autocode_template/server/model.go.tpl
- server/resource/autocode_template/server/request.go.tpl
- server/resource/autocode_template/server/service.go.tpl
- server/resource/autocode_template/web/table.vue.tpl
- server/service/system/sys_auto_code.go
- server/service/system/sys_auto_code_mssql.go
- server/service/system/sys_auto_code_mysql.go
- server/service/system/sys_auto_code_oracle.go
- server/service/system/sys_auto_code_pgsql.go
- server/service/system/sys_auto_code_sqlite.go
- web/src/view/systemTools/autoCode/component/fieldDialog.vue
- web/src/view/systemTools/autoCode/index.vue
> 自动化代码可选不使用官方global.Model结构

- server/initialize/router.go
> 通过后端代理静态资源目录错误

- web/src/utils/dictionary.js
优化字典文字展示方法
新增可配置的参数 keyCode 和valueCode 使用字典字段更加灵活
> dictionary.js update  优化字典文字展示方法

- server/middleware/operation.go
fix:修改操作记录中间件，文件类型统一记录为[文件]，若为其他，则判断是否超出内容长度，超出则记录为[超出记录长度]
> fix:修改操作记录中间件，文件类型统一记录为[文件]

- web/src/utils/request.js
> fix the word spelling error for acitveAxios

- server/api/v1/system/sys_export_template.go
- server/initialize/gorm.go
- server/model/system/sys_export_template.go
- server/service/system/sys_export_template.go
- web/src/components/exportExcel/exportExcel.vue
- web/src/view/superAdmin/api/api.vue
- web/src/view/systemTools/exportTemplate/exportTemplate.vue
feature:表格导出支持配置limit order和where条件
> feature:表格导出支持配置limit order和where条件

- server/service/system/sys_export_template.go
> fix:保证excel每次导出列顺序一致

- server/service/system/sys_export_template.go
Reverts flipped-aurora/gin-vue-admin#1677
> Revert "fix:保证excel每次导出列顺序一致"

- web/src/api/initdb.js
- web/src/api/user.js
- web/src/utils/request.js
- web/src/view/layout/index.vue
- web/src/view/login/index.vue
> loading增加定制属性，可自行配置

- server/model/system/request/sys_menu.go
- server/model/system/sys_authority_menu.go
- server/model/system/sys_base_menu.go
- server/plugin/plugin-tool/utils/check.go
- server/service/system/sys_authority.go
- server/service/system/sys_auto_code.go
- server/service/system/sys_base_menu.go
- server/service/system/sys_menu.go
- server/source/system/menu.go
- web/src/view/superAdmin/menu/menu.vue
> fixed:菜单删除功能细节调优

- server/service/system/sys_authority.go
- server/service/system/sys_dictionary.go
- server/service/system/sys_user.go
更新用户、角色、字典更新时，将查询和更新分开
代码在MySQL和PG中都通过
> 多文件: fix error specified more than once in PG

- server/go.mod
- server/go.sum
- server/service/system/sys_authority.go
- server/service/system/sys_dictionary.go
- server/service/system/sys_export_template.go
- server/service/system/sys_user.go
修复pgsql和数据库导入bug，增加默认mod中的datatypes
> 修复pgsql和数据库导入bug，增加默认mod中的datatypes

- server/resource/autocode_template/server/api.go.tpl
> fix(bug): [api.go.tpl]自动化代码swag路径冲突

- web/index.html
- web/src/main.js
- web/src/view/layout/components/loading.vue
> Add loading

- server/api/v1/system/sys_export_template.go
- server/service/system/sys_api.go
- server/service/system/sys_casbin.go
- server/service/system/sys_dictionary.go
- server/service/system/sys_operation_record.go
- server/service/system/sys_user.go
经过多个版本的迭代，一些方法的注释还是之前的没及时修改，本次提交是将方法名和注释对应起来
> perf: 优化 api 和 service 中方法注释不正确的问题

- server/service/system/sys_api.go
[fixed] 去除不必要错误判断，增加ClearCasbin失败判断
> [sys_api.go]: 优化代码

- web/.gitignore
- web/src/components/warningBar/warningBar.vue
- web/src/config.json
- web/src/pinia/modules/app.js
- web/src/style/main.scss
- web/src/view/dashboard/index.vue
- web/src/view/layout/aside/asideComponent/asyncSubmenu.vue
- web/src/view/layout/aside/asideComponent/index.vue
- web/src/view/layout/aside/asideComponent/menuItem.vue
- web/src/view/layout/aside/head.vue
- web/src/view/layout/aside/index.vue
- web/src/view/layout/aside/normal.vue
- web/src/view/layout/header/index.vue
- web/src/view/layout/index.vue
- web/src/view/layout/setting/index.vue
> fix: 优化前端 layout， 添加顶部菜单

- server/config.yaml
- server/config/zap.go
- server/core/internal/cutter.go
- server/core/internal/zap_core.go
gva项目新增对logs下文件夹的定期清理功能，也可配置不清理，较原框架有改进。
> gva项目新增对logs下文件夹的定期清理功能，也可配置不清理，较原框架有改进。

- server/model/system/sys_auto_code.go
- server/service/system/sys_auto_code.go
- web/src/config.json
- web/src/pinia/modules/router.js
- web/src/style/element_visiable.scss
- web/src/view/layout/aside/combinationMode.vue
- web/src/view/layout/aside/index.vue
- web/src/view/layout/header/index.vue
- web/src/view/layout/index.vue
- web/src/view/layout/setting/index.vue
- web/src/view/systemTools/autoCode/index.vue
- web/src/view/systemTools/system/system.vue
> feat: 优化自动化代码结构，增加顶栏侧边栏组合式结构

- web/src/pinia/modules/app.js
[调整配置文件默认灰度不生效问题](https://github.com/flipped-aurora/gin-vue-admin/commit/7f0f5eaaf7d90858b6fcf533e2bab2d259da91f2)
> 调整配置文件默认灰度不生效问题

- web/src/view/superAdmin/api/api.vue
> api.vue：update：修改API分组为下拉列表

- web/src/pinia/modules/user.js
> fix(user-store): add cookie support for language selection

- server/resource/plugin/server/initialize/router.go.template
- server/utils/ast/package_initialize_gorm.go
- server/utils/ast/plugin_initialize_gorm.go
- server/utils/ast/plugin_initialize_router.go
> 2.7.0Beta2

- web/src/view/superAdmin/user/user.vue
修复userInfo username拼写错误，目前用户注册数据多一行username
`{
"username": "",
"password": "123qweasd",
"nickName": "Testb",
"headerImg": "https://qmplusimg.henrongyi.top/gvalogo.png",
"authorityId": 888,
"authorityIds": [888, 8881],
"enable": 1,
"userName": "Testb"
}`
> chore(user.vue): Update user.vue, alter userInfo username to userName.

- server/api/v1/example/exa_breakpoint_continue.go
- server/api/v1/system/auto_code_plugin.go
- server/api/v1/system/sys_authority.go
- server/api/v1/system/sys_auto_code.go
> feature: swagger接口请求优化

- server/resource/plugin/server/service/service.go.template
> 修改模板，去除 生成代码  service 多余空格 

- server/config.yaml
- server/config/config.go
- server/config/redis.go
- server/core/server.go
- server/global/global.go
- server/initialize/redis.go
通过在配置文件配置 redis-list 字段：
```yaml
redis-list:
- name: cache           # 数据库的名称,注意: name 需要在 redis-list 中唯一
useCluster: false     # 是否使用redis集群模式    
addr: 127.0.0.1:6379  # 使用集群模式addr和db默认无效
password: ""
db: 0
clusterAddrs:
- "172.21.0.3:7000"
- "172.21.0.4:7001"
- "172.21.0.2:7002"
```
可以在业务中使用不同的 Redis 实例：
```go
cachaRedis := global.GetRedis("cache")
// do somthing with cachaRedis
```
> redis list 支持

- server/model/common/basetypes.go
Reverts flipped-aurora/gin-vue-admin#1884
> Revert "Update basetypes.go, fixed origin_setting column read error"

- web/src/view/layout/header/index.vue
> clean: clean header index.vue repeat flex class

- server/api/v1/system/sys_user.go
adjust sys_user.go message when del logined self
调整登录用户删除自己时的提示。减少在客户面前 "调皮" 后的不适感。
> 修改删除用户提示："自杀失败" -> "无法删除自己。"

- server/resource/package/web/view/table.vue.tpl
1.查询条件字段，如果关联业务表下拉查询，则参考form使用下拉框。
2.新增和添加统一，变更和修改统一，查看详情弹框增加标题查看
> 修改模板文件table.vue.tpl

- server/resource/package/web/view/table.vue.tpl
- server/resource/plugin/web/view/view.vue.template
- web/src/plugin/announcement/view/info.vue
- web/src/utils/format.js
- web/src/view/superAdmin/api/api.vue
- web/src/view/superAdmin/operation/sysOperationRecord.vue
- web/src/view/superAdmin/params/sysParams.vue
- web/src/view/systemTools/exportTemplate/exportTemplate.vue
设置了一页条数后 再查询会重置条数，pageSize有默认值不需要每次查询都重置，影响体验
> 查询不重置pageSize

- web/src/view/superAdmin/menu/icon.vue
- web/src/view/systemTools/autoCode/index.vue
- web/src/view/systemTools/system/system.vue
layout/admin/menu
解决Invalid vnode type when creating vnode的警告问题
> 解决Invalid vnode type when creating vnode的警告问题

- web/src/view/superAdmin/menu/icon.vue
- web/src/view/systemTools/autoCode/index.vue
- web/src/view/systemTools/system/system.vue
> Neo 6 patch 2

- server/api/v1/system/auto_code_plugin.go
- server/api/v1/system/auto_code_template.go
- server/initialize/ensure_tables.go
- server/initialize/gorm_mssql.go
- server/model/system/request/sys_casbin.go
- server/model/system/request/sys_menu.go
- server/model/system/request/sys_user.go
- server/service/example/exa_breakpoint_continue.go
- server/service/system/auto_code_template.go
- server/service/system/sys_casbin.go
- server/source/example/file_upload_download.go
- server/source/system/api.go
- server/source/system/api_ignore.go
- server/source/system/authorities_menus.go
- server/source/system/authority.go
- server/source/system/casbin.go
- server/source/system/dictionary.go
- server/source/system/dictionary_detail.go
- server/source/system/excel_template.go
- server/source/system/menu.go
- server/source/system/user.go
- server/utils/ast/ast.go
- server/utils/ast/ast_gorm.go
- server/utils/fmt_plus.go
- server/utils/jwt.go
- server/utils/timer/timed_task.go
- web/Dockerfile
- web/src/components/exportExcel/exportExcel.vue
- web/src/components/exportExcel/exportTemplate.vue
- web/src/components/exportExcel/importExcel.vue
> docs:调整部分代码注释以及代码格式

- Makefile
- server/core/server.go
- server/main.go
+ fix: 修复欢迎信息中的 tab 缩进格式
+ `Makefile` 文件添加 make doc 构建步骤，用于生成 swagger 文档
+ 添加 swagger 文档接口排序的 `@Tag` 设置说明，具体结果参考图片
> 注：自己没有上次已经重新生成的 swagger 文档
> 添加 swagger 文档接口排序的 @Tag 设置说明

- Makefile
- server/service/system/auto_code_package.go
- server/service/system/auto_code_template.go
- server/service/system/sys_api.go
- server/service/system/sys_export_template.go
* **Makefile**: 使用 `?=` 替代 if-else 的判断
* 移除多余的类型转换
* 移除多余的 `nil` 判断
* map 使用简化以及错误处理优化
> 代码优化及错误返回改进

- web/src/api/autoCode.js
- web/src/view/systemTools/autoCode/index.vue
> 给自动化代码增加视觉功能

- server/service/system/sys_authority.go
> fixed: 修复递归获取角色列表数据缺失问题

- web/src/api/fileUploadAndDownload.js
- web/src/components/Avatar/ProfileAvatar.vue
- web/src/view/person/person.vue
> 更新个人信息页样式 这个头 得开

- web/src/components/selectImage/selectComponent.vue
> [selectComponent.vue]上传组件支持查看大图

- server/router/system/sys_export_template.go
> fix: 修改导入excel模板数据注释

- server/resource/package/web/view/table.vue.tpl
- server/resource/plugin/web/view/view.vue.template
- web/src/components/selectFile/selectFile.vue
有公共函数onDownloadFile，去掉downloadFile
> 有公共函数onDownloadFile，去掉downloadFile

- server/initialize/gorm_mysql.go
- server/initialize/gorm_oracle.go
- server/initialize/gorm_pgsql.go
- server/initialize/gorm_sqlite.go
> GORM初始化数据库优化，通过抽取重复的逻辑避免代码冗余。

- README-en.md
- README.md
Hi flipped-aurora/gin-vue-admin Team
We’re the team behind Openomy, We can now prepare a contributor chart exclusively for your community, and we are excited to offer a brand-new contribution visualization chart for your GitHub repository, ready to be embedded directly into your README.
Unlike GitHub’s default contributor chart, the Openomy chart offers a more comprehensive view of community contributions. In addition to code-related actions like commits and pull requests, we also recognize other meaningful activities such as issues, comments, and even likes—because we believe every act of participation deserves to be seen and valued.
We’ve created a personalized data detail page in flipped-aurora/gin-vue-admin
[flipped-aurora/gin-vue-admin](https://www.openomy.app/github/flipped-aurora/gi …
> docs: update a new contributions charts with Openomy

- server/resource/package/server/model/request/request.go.tpl
- server/resource/package/server/service/service.go.tpl
- server/resource/plugin/server/model/request/request.go.tpl
- server/resource/plugin/server/service/service.go.tpl
mysql不支持ISO8601时间的搜索，会忽略掉传入时区，导致查询丢失时区精度
> fix: 修正搜索时间范围传入ISO8601字符串导致MySQL查询出错，并优化nil切片len检查（S1009）

- web/src/view/systemTools/autoCode/index.vue
在生成代码的时候点击暂存没用反应 有点不友好 我给添加了一个提示 效果如图
> feat: 添加暂存成功提醒

- server/service/system/sys_export_template.go
Reverts flipped-aurora/gin-vue-admin#2033
> Revert "修正导出execl中数字为文本格式问题"

- server/utils/autocode/template_funcs.go
> 系统生成文件，当需要手动实现增加TODO标识

- server/service/system/sys_export_template.go
> 修正导出execl中数字为文本类型问题

- server/mcp/gva_auto_generate.go
- server/service/system/auto_code_package.go
- web/package.json
refactor(analyzer): 重构模块分析逻辑，增加空包检测
> feat(autoCode): 添加空包检测与自动清理功能

- server/utils/upload/minio_oss.go
minio上传根据文件扩展名检测 MIME 类型
以设置正确的content-type供浏览器或者大模型识别
经测试gemini多模态会严格检查content-type类型,修复后识别正常
> feat: set correct content-type for minio upload
