flipped-aurora/gin-vue-admin

- docker-compose.yml
如果你安装了Docker，便可以迅速部署本项目所需要的MySQL数据库。
https://github.com/piexlmax/gin-vue-admin/issues/16 中提到的方法启发了我，但是，我没能部署所有的服务。
希望以后有机会可以完善这个Compose文件。
Docker的版本不能低于 `17.12.0+` 。Docker的版本与Compose文件的 `version` 相关，请参考以下链接：
https://docs.docker.com/compose/compose-file/#compose-and-docker-compatibility-matrix
在 `docker-compose.yml` 所在的目录下
- 启动MySQL：`docker-compose up -d`
- 关闭MySQL：`docker-compose down`
- 删除数据卷：`docker volume prune -f`
> Add a docker compose file to setup MySQL

- QMPlusServer/Dockerfile
- QMPlusServer/init/qmsql/initMysql.go
- QMPlusServer/main.go
- docker-compose.yml
容器化后端服务。在编排容器时已经进行了端口映射。在宿主机中可以正常查看swagger构建的文档。
- 在首次使用，或者更新过 `QMPlusServer` 目录下的 `Dockerfile` 之后，必须运行： `docker-compose build`
- 日常使用时只需要： `docker-compose up -d`
> Containerize QMPlusServer

- server/core/config.go
- server/packfile/notUsePackFile.go
- server/packfile/usePackFile.go
与当前默认方式不冲突  
使用方式
```bash
go get -u github.com/go-bindata/go-bindata/...
cd server
// 如果提示找不到go-bindata，请排查下 $GOPATH/bin 是否在环境变量中
go generate -tags=packfile ./packfile/usePackFile.go   
go build -tags=packfile
```
即可将该二进制文件放置到任何位置运行，不再需要`resource/...` `config.yaml`  
程序启动时，会将`go build`时存储到二进制中的快照，写入到当前目录对应位置。  
写入到磁盘的行为，只会在文件不存在时进行写入，不会覆盖。
本地简单测试无问题，如有问题我会进行`fix`。
> 打包静态文件到二进制

- server/global/response/response.go
- server/go.mod
- server/middleware/cors.go
safari, 360 IE10以下的浏览器不支持*, origin的获取改为从header中获取
> cors.go: fix部分浏览器不支持*的格式

- web/src/components/upload/image.vue
- web/src/utils/image.js
- web/src/view/example/upload/upload.vue
文件上传前前端处理压缩，
可以设置执行文件大小阀值（kb）， 压缩后的文件尺寸上限（像素）
----------------------------------------------------------
TODO: 上传接口token
压缩前后对比
> 图片上传压缩（前端）及示例

- server/api/v1/sys_user.go
- server/config.yaml
- server/config/gorm.go
- server/initialize/gorm.go
- server/initialize/logger.go
- server/utils/verify.go
- 修改文件：
server/initialize/gorm.go
server/config/gorm.go
server/config.yaml
server/utils/verify.go
server/api/v1/sys_user.go
- 功能实现：
自定义logger保留gorm的格式输出控制台, 修改SetUserInfo的校验规则为IdVerify
- 实现功能说明：
自定义gorm的logger所需要的接口，使用全局zap自定义打印规则,实现日志可以通过zap记录入本地log文件里
- 注意事项
`config.yaml` 中 `mysql` 下的 `log-zap` 的值为 `"Silent"` , `"Error"`, `"Warn"`, `"Info"`
```yaml
mysql:
path: '127.0.0.1:3306'
config: 'charset=utf8mb4&parseTime=True&loc=Local'
db-name: 'qmPlus'
username: 'root'
password: 'Aa@6447985'
max-idle-conns: 10
max-open-conns: 100
log-mode: false
log-zap: false
log-zap: ""
```
gorm的sql日志记录使用`zap`持久化是使用`log-zap: false`, `log-zap: "Info"`
> 自定义logger保留gorm的格式输出控制台, 修改SetUserInfo的校验规则为IdVerify

- server/resource/template/web/table.vue.tpl
修改自动生成代码，当table数据大于50条时，页面会卡死，替换掉 el-popover即可。
> 修复table数据大于50条时页面卡死

- server/config.yaml
- server/config/oss.go
- server/utils/upload/aliyun_oss.go
- web/src/components/upload/image.vue
- server端解决oss上传图片提交路径和存储路径不一致
- web端解决上传成功后封装的upload-image组件展示路径多加一个绝对路径后图片无法正常展示
> [修复阿里云OSS图片上传路径不一致错误]

- server/core/server.go
- server/core/viper.go
1.viper加载时global.GVA_DB 还未初始化，无法从数据库加载jwt黑名单数据，所以把system.LoadAll()移动到core/server.go中
2.gkit的local_cache SetDefault方法中，DefaultExpire固定为0（看源码应该是gkit的bug），所以导致cache中的jwt黑名单只要一访问就会被删除从而导致jwt黑名单无效，所以改用SetNoExpire
> bug修复：jwt黑名单启动时候未加载及未生效

- web/src/view/dashboard/dashbordCharts/echartsLine.vue
- web/src/view/layout/aside/historyComponent/history.vue
- web/src/view/layout/aside/index.vue
- web/src/view/layout/screenfull/index.vue
- web/src/view/system/state.vue
Vue3中生命周期已不存在`beforeDestroy`钩子，已由`beforeUnmount`代替，参考文档：https://v3.cn.vuejs.org/api/options-lifecycle-hooks.html#beforeunmount
- Vue3文档中改变说明：https://v3.cn.vuejs.org/guide/migration/introduction.html#%E5%85%B6%E4%BB%96%E5%B0%8F%E6%94%B9%E5%8F%98
> 修正生命周期钩子，将`beforeDestroy`更改为`beforeUnmount`

- server/utils/directory.go
当存在同名文件时，utils.PathExists()返回false, errors.New("存在同名文件")
> fix(utils/directory.go): 同名文件存在时正确返回

- server/utils/file_operations.go
同名目录存在时，utils.FileExist()返回false
> fix(utils/file_operations.go): 同名目录存在时正确返回

- web/src/view/layout/aside/asideComponent/asyncSubmenu.vue
- web/src/view/layout/aside/asideComponent/menuItem.vue
- web/src/view/superAdmin/menu/menu.vue
菜单的icon本身为可选项，但未设置菜单的icon时，vue会发出警告：
Invalid vnode type when creating vnode: .  at <ElIcon> 
这是由于routerInfo.meta.icon为空时，将空字符串交由el-icon去渲染图标导致的。现用v-if指令避免这种情况发生。
> bugfix:修复菜单未设置icon时，vue会弹出vnode警告的bug；

- server/middleware/operation.go
> server/middleware/operation.go : fix 当记录日志当请求为GET时，不对query参数进行记录

- web/src/view/layout/aside/historyComponent/history.vue
route1.query={}
route2.query={a:1}
route1的query,params为空时，还是会返回true
> 这个isSame有问题

- server/service/system/sys_api.go
- server/service/system/sys_base_menu.go
related issue: #936 
当此接口`/api/getApiList`入参`orderKey`不为以下["id","path","api_group","description","method"]之一时 ,即可复现。
当接口入参`orderKey`非法时，如“ID”,执行到下游函数`func (apiService *ApiService) GetAPIInfoList`中时会导致:`OrderStr==""`，从而此处`err = db.Order(OrderStr).Find(&apiList).Error`构造出#936 所描述异常SQL语句。
加入else分支捕捉`apiService.GetAPIInfoList`函数入参order不为空但非法的情况。如非法的order值即报错返回。
> Fix invalid orderKey

- server/service/system/sys_system.go
- server/utils/server.go
service/system/sys_system.go:43 查看服务器信息的函数返回结构体里的错别字，对逻辑无影响
utils/server.go:22 Rrm改为Ram
> 修改了Ram拼写错误

- web/src/permission.js
复现步骤:
1. 登录后拉黑 Token 或将 localStorage 里的 Token改为任意值
2. F5 刷新页面
3. 页面提示 "That's not even a token"  "未登录或非法访问", 并导致了白屏无响应
控制台报错:
`
[Vue Router warn]: Unexpected error when starting the router: RangeError: Maximum call stack size exceeded
at Object.resolve (vue-router.esm-bundler.js:1406:5)
at resolve (vue-router.esm-bundler.js:2912:38)
at pushWithRedirect (vue-router.esm-bundler.js:3000:51)
at pushWithRedirect (vue-router.esm-bundler.js:3008:20)
at pushWithRedirect (vue-router.esm-bundler.js:3008:20)
at pushWithRedirect (vue-router.esm-bundler.js:3008:20)
at pushWithRedirect (vue-router.esm-bundler.js:3008:20)
at pushWithRedirect (vue-router.esm-bundler.js:3008:20)
at pushWithRedirect (vue-router.esm-bundler.js:3008:20)
at pushWithRedirect (vue-router.esm-bundler.js:3008:20)
`
原因: 
执行 …
> 修复 Token 失效后导致的白屏问题

- Dockerfile
- Makefile
- entrypoint.sh
- server/api/v1/system/sys_user.go
- server/model/system/request/sys_user.go
- web/.docker-compose/nginx/conf.d/nginx.conf
功能一：提交main分支代码，会自动更新镜像
registry.cn-hangzhou.aliyuncs.com/gva/web:latest
registry.cn-hangzhou.aliyuncs.com/gva/server:latest
registry.cn-hangzhou.aliyuncs.com/gva/all:latest
功能二：增加尝鲜版镜像，不适合应用于生产，只用于体验功能
docker run -d -p 8080:8080 -p 8888:8888 registry.cn-hangzhou.aliyuncs.com/gva/all
启动后需要等待2分钟，初始化不需要更改任何数据，直接点击确认即可
附：前后端数据库三合一镜像demo，可使用make image创建
docker run -d -p 80:80 registry.cn-hangzhou.aliyuncs.com/gva/all-one
由于是打过包的，没有自动化创建代码功能。
功能三：增加make命令，其中go后端使用-ldflags镶入版本号
#前后端共同容器内打包
make build
#本地环境打包前后端
make build-local
#容器内打包前端
make build-web
#本地环境打包前端
make build-web-local
#容器打包后端
make build-server
#本地环境打包后端
make build-server-local
#构建本地web镜像
make build-image-web
#构建本地server镜像
make build-image-server
#制作前后端打包版二合一镜像
make image
> 增加make命令操作，以及自动化流程

- server/source/system/api.go
会造成的问题是：项目初始化后，在菜单管理页面可以看到这个api的方式是post，然后再角色管理里面，普通用户的角色api的分片上传组-寻找目标文件（秒传）是没有选中的，如果勾选上点击确定提交，会造成断点续传功能无法上传文件，casbin校验不通过，因为数据被修改了。
如果对角色api这个复选框没有选中的情况不进行操作的话，不影响断点续传功能使用。
> 修复分片上传-寻找目标文件（秒传）的请求方式有误

- server/model/system/request/sys_init.go
https://www.postgresql.org/docs/current/app-initdb.html
The postgres database is a default database meant for use by users, utilities and third party applications.
默认数据库postgres一般存在,但用户名同名数据库不一定存在
> fix: 修复初始化PostgreSQL时尝试数据库连接验证时用户名同名数据库不存在导致的初始化失败问题

- server/core/internal/constant.go
- server/core/viper.go
- server/utils/constant.go
- 为了对原系统破坏性最低，server/core/viper.go 的 33,34行 定义为config.yaml
如果想要标准化 开发,测试,生产 三个环境的config不一样, 可用以下代码代替 server/core/viper.go的33,34行
```go
config = internal.ConfigDebugFile
fmt.Printf("您正在使用gin模式的%s环境名称,config的路径为%s\n", gin.EnvGinMode, internal.ConfigDebugFile)
```
- 注意设置gin的环境变量 GIN_MODE 时，GIN_MODE 只能有三个值，debug、release、test， 其他值会panic的
> feature: viper 读取gin自带的环境变量GIN_MODE,用于区分开发,测试,生产三个环境 #1098

- server/config/zap.go
- server/core/internal/file_rotatelogs.go
- server/core/internal/zap.go
- server/core/zap.go
- zap日志无法按照等级出现在对应log文件中
- zap.AddCaller()只有在global.GVA_CONFIG.Zap.ShowLine为true才生效
- rotatelogs.ForceNewFile(),取消这个, 这样每次启动不会出现同一天日志级别.1后缀的新文件
> 修复issues #1118

- server/api/v1/system/sys_user.go
如果在这里数据库查询出现错误，err != nil 就会两次返回 出现返回结果为
{"code":7,"data":{},"msg":"设置失败"}{"code":0,"data":{},"msg":"设置成功"}
这种形式，导致vue js无法正确处理返回
> 修复BUG，如果在这里数据库查询出现错误会导致问题

- server/embed.go
- server/main.go
基于 #377 pr修改 ，已带原作者信息
1. mac测试通过，windows未测试
2. 需要review代码，不确实有无未知bug
3. 如果有自己的静态文件，不想放在resource中，就自行到 `server/embed.go` 的 `resource embed.FS`上方写上注册 `//go:embed 文件夹名称或者文件名称`，需要注意的是，go build 时必须要保证与`resource embed.FS`上方注释的文件或者文件夹存在
> feature: 根据 #377 pr进行修改embed, 打包静态文件夹与配置文件

- gin-vue-admin.code-workspace
折磨我两个小时的BUG
手动go build可以
goland可以
VSCODE编译/调试就不行
> BUGFIX. VSCode工作区文件配置文件调整，使调试功能兼容最近添加的embed.go

- server/api/v1/system/sys_user.go
- server/model/system/request/sys_user.go
- server/model/system/sys_user_authority.go
- server/service/system/sys_authority.go
- server/service/system/sys_user.go
- server/utils/verify.go
- web/src/view/person/person.vue
- 修改密码（`ChangePassword()` ）改为使用 id 查询
- 从jwt中获取目标用户id，而非不校验地使用 `username` （任意登录用户只要知道另一个用户的密码都可以改他的密码）
- 修了一个命名错误
> 修改密码使用 jwt 中的用户ID，防止越权

- web/src/style/button.scss
- web/src/view/superAdmin/authority/components/apis.vue
- web/src/view/superAdmin/authority/components/menus.vue
优化角色管理中菜单和api管理的确定按钮，固定在右上角，更容易操作，每次修改完不需要拉到最上面再确定
> 优化角色管理中菜单和api管理的确定按钮，固定在右上角，更容易操作，每次修改完不需要拉到最上面再确定

- server/api/v1/system/sys_auto_code.go
- server/config/config.go
- server/config/gorm_oracle.go
- server/initialize/db_list.go
- server/initialize/gorm_oracle.go
- server/initialize/internal/gorm.go
- server/service/system/sys_auto_code_interface.go
- server/service/system/sys_auto_code_mysql.go
- server/service/system/sys_auto_code_oracle.go
- server/service/system/sys_auto_code_pgsql.go
- web/src/api/autoCode.js
- web/src/view/systemTools/autoCode/index.vue
自动化代码支持前端从业务库选择表，增加业务库支持Oracle类型。 由于使用的Oracle驱动( godror )需要 cgo 支持，暂时把 gorm_oracle里 oracle改为了mysql ，如有需要 可按注释说明替换即可
> 自动化代码支持前端从业务库选择表

- web/src/view/layout/aside/asideComponent/asyncSubmenu.vue
- web/src/view/layout/aside/asideComponent/menuItem.vue
左侧菜单item，图标和左侧边距太紧。增加item项的左内边距，让图标和边框之间有6px间距，看起来美观一点。
目录菜单也是同样的处理。
> feat:'左侧菜单item修改左内边距'

- server/model/system/response/sys_captcha.go
去除结构体 SysCaptchaResponse 字段CaptchaLength 的 json tag 多余的双引号
> @sakishum 去除 json tag 多余的双引号

- web/src/utils/request.js
如果有接口的donNotShowLoading设置为true的时候,没有判断这个值的情况下直接调用closeLoading,会导致acitveAxios一直累减,然后下个需要显示loading的接口,就无法显示loading了,因为acitveAxios的值仍然小于0
1.增加三个接口
```
export const GetData = () => {
return service({
url: '/api/getdata',
method: 'GET'
})
}
export const NotShowOne = () => {
return service({
url: '/api/test1',
method: 'GET',
donNotShowLoading: true
})
}
export const NotShowTwo = () => {
return service({
url: '/api/test1',
method: 'GET',
donNotShowLoading: true
})
}
```
2.点击按钮依次调用上面的接口,第一次调用的时候GetData接口的loading显示正常.由于没有判断donNotShowLoading是否为true就直接closeLoading(),导致acitveAxios的值和接口调用次数不一致,就会导致第二次调用GetData接口的时候,loading无法显示
> closeLoading()的时候先判断接口是否开启了loading,解决showLoading()失效问题

- server/config.yaml
- server/initialize/router.go
- server/middleware/cors.go
解决这个[issue](https://github.com/flipped-aurora/gin-vue-admin/issues/1293)
这个issue产生的原因是可能是（不确定用户实际怎么写的） allow-headers是配置少了一些字段。
我这次加上下面这些，白名单就能正常工作了。已经测试。
```
allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
```
> bugfix: 通过修改配置文件使得跨域白名单正常生效

- server/service/system/sys_authority.go
DeleteAuthority方法修改没有正确处理err导致返回的err信息不正确
GetAuthorityInfoList方法取消多余的if判断,减少阅读疑惑
> fix:service\system\sys_authority.go:修改没有正确处理err;取消多余if 判断

- server/go.mod
- server/go.sum
There are 1 security vulnerabilities found in nhooyr.io/websocket v1.8.6
- [MPS-2022-13514](https://www.oscs1024.com/hd/MPS-2022-13514)
Upgrade nhooyr.io/websocket from v1.8.6 to 1.8.7 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
> fix(sec): upgrade nhooyr.io/websocket to 1.8.7

- server/service/system/sys_auto_code.go
原本 for 循环下 if 判断只有 HasTimer 判断，加了 break 可以提前跳出循环，但另外新增了 NeedValid 和 NeedSort 判断后，直接跳出循环会导致无法正常设置 HasTimer ，NeedValid 和 NeedSort
> fixbug: 修复代码生成器无法自动导入 time 包问题

- server/service/system/sys_dictionary.go
直接使用Preload加载的字典值是按ID排序的，在前端展示时并非希望的sort排序
> fix: 修复字典按ID排序而非sort排序问题

- server/go.mod
- server/go.sum
- server/service/system/sys_casbin.go
CachedEnforcer不支持多并发场景，当API并发请求时服务会报出：fatal error: concurrent map writes。
解决方法：使用SyncedCachedEnforcer替换CachedEnforcer。
具体原因见：https://github.com/casbin/casbin/issues/1214
> fix: 修复并发请求API情况下的读写冲突问题

- server/config.docker.yaml
- server/config.yaml
配置文件中引用的 server/initialize/router.go#L32 由于文件修改，已经不是跨域配置相关的代码，产生了歧义
> 避免配置文件的注释中引用行号变更带来的歧义

- server/go.mod
- server/go.sum
There are 1 security vulnerabilities found in golang.org/x/image v0.0.0-20210220032944-ac19c3e999fb
- [CVE-2022-41727](https://www.oscs1024.com/hd/CVE-2022-41727)
Upgrade golang.org/x/image from v0.0.0-20210220032944-ac19c3e999fb to 0.5.0 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
> fix(sec): upgrade golang.org/x/image to 0.5.0

- web/vitePlugin/codeServer/index.js
> fix: macos和linux下代码定位命令不对 #1495

- server/utils/timer/timed_task.go
Add：Timer工具增加AddTaskByFuncWithSeconds与AddTaskByJobWithSeconds方法 Fix：解决添加定时任务没有按时运行问题
// AddTaskByFuncWithSeconds 通过函数的方法使用WithSeconds添加任务 func (t *timer) AddTaskByFuncWhithSecond(taskName string, spec string, task func(), option ...cron.Option) (cron.EntryID, error) {
t.Lock()
defer t.Unlock()
option = append(option, cron.WithSeconds())
if _, ok := t.taskList[taskName]; !ok {
t.taskList[taskName] = cron.New(option...)
}
id, err := t.taskList[taskName].AddFunc(spec, task)
t.taskList[taskName].Start()
return id, err
}
// AddTaskByJobWithSeconds 通过接口的方法添加任务
func (t *timer) AddTaskByJobWithSeconds(taskName string, spec string, job interface{ Run() }, option ...cron.Option) (cron.EntryID, error) {
t.Lock()
defer t.Unlock()
option = append(option, cron.WithSeconds())
if _, ok := …
> 更新 timed_task.go 增加了两个方法

- server/service/example/exa_file_upload_download.go
> feat:抛出上传文件错误信息

- server/resource/autocode_template/server/service.go.tpl
分页获取数据接口，增加判断pagesize，如果不传分页参数或pagesize为0，不分页返回所有数据。
> 分页列表接口，兼容不分页获取全部数据

- web/src/view/layout/index.vue
修改为tailwindcss后，添加遮罩时没有判断是否为手机端
> fix: 修复菜单折叠后再次展开右侧出现遮罩的问题

- server/resource/autocode_template/web/table.vue.tpl
table的批量删除按钮，未选中内容时候，悬浮提醒不应该显示。增加以下代码
:disabled="!multipleSelection.length"
> 批量删除按钮，未选中内容时，悬浮不应该显示对话框

- server/core/internal/cutter.go
- server/core/internal/file_rotatelogs.go
- server/core/internal/zap.go
- server/go.mod
- server/go.sum
- 去掉 github.com/lestrrat-go/file-rotatelogs 库的依赖
- 实现zap.String(…"business", "xx")自定义业务日志数据路径, 输出文件路径为./global.GVA_CONFIG.Zap.Director/2006-01-02/xx/level(debug, info, warn, error, dpanic, panic, fatal).log
> update: zap 日志切割优化

- server/middleware/operation.go
- server/utils/captcha/redis.go
operation.go: fix 调用respPool.Put归还对象前清空对象会造成下次调用无法copy
redis.go: fix NewDefaultRedisStore方法实例化的对象直接使用会造成空指针异常
> fix 调用respPool.Put归还对象前清空对象会造成下次调用无法copy

- web/src/view/routerHolder.vue
新建二级菜单使用 web/src/view/routerHolder.vue 或参考该文件自建文件后，点击新建的菜单会有警告：Component inside <Transition> renders non-element root node that cannot be animated
<keep-alive> 包裹的组件添加一层div后，有单一的根元素，并且在 <transition> 中也只有一个根元素，能够避免这个警告
> web/src/view/routerHolder.vue：Fix 消除vue二级菜单组件警告 

- server/service/system/sys_auto_code.go
https://github.com/flipped-aurora/gin-vue-admin/issues/1633
> 代码打包的插件，从后台安装失败，认不到目录的问题

- web/src/view/superAdmin/user/user.vue
修改头像打开素材库时层级错误，drawer应该在dialog的上方
> 解决drawer和dialog层级冲突问题

- server/service/system/sys_api.go
> fix: 更新api路径时使用`binary`区分大小写进行查询

- web/.env.production
- web/src/view/superAdmin/menu/icon.vue
修复新增菜单强制默认icon的bug。
在项目中新增菜单是一个经常会用到的功能，特别是项目初期会频繁的增加菜单。有很多菜单是不需要添加icon的，所以创建菜单给定一个默认icon对用户来说是一个负担。
修复production环境变量容易造成困惑的问题。
我的团队在每次新项目中使用GVA时，都会在production的环境变量上有困惑，其中存在很多不必要的配置（来自于development），我认为应该优化掉。
> bugfix:修复新增菜单强制默认icon的bug；修复production环境变量容易造成困惑的问题；

- web/vite.config.js
fix: 解决build时，会有浏览器缓存问题。
我在使用最新版本的代码时，发现打包配置添加了`rollupOptions`，多了一个`087AC4D233B64EB0`，我没去回顾commit，但我尊重原代码。不过这样会造成生产环境的浏览器缓存问题。我添加了hash来避免这个问题。
> fix: 解决build时，会有浏览器缓存问题。

- server/config/system.go
- server/initialize/router.go
- server/middleware/casbin_rbac.go
- web/src/view/systemTools/system/system.vue
> feat(gin.Mode()): 由环境变量决定，不再依赖于配置文件system.Env

- web/src/view/superAdmin/api/api.vue
popover默认为hover，鼠标略过的时候，会直接弹出气泡，并且此时还可以直接对气泡内的按钮进行操作，不太符合操作逻辑
原来的：
修改后：
> fixed:  api管理中删除的 popover 触发改为 click

- deploy/docker-compose/docker-compose-dev.yaml
- deploy/docker-compose/docker-compose.yaml
Adding Health Check to Docker Compose Deployment
Description:
This pull request introduces a health check mechanism to the Docker Compose deployment of our repository. With this enhancement, we ensure better monitoring and resilience of our services.
Changes:
Added health check configurations to the Docker Compose file.
Implemented health checks for each service in the deployment.
Verified the functionality locally and ensured seamless integration with the existing setup.
Benefits:
Improved reliability: Health checks enable early detection of service failures, ensuring faster response times to potential issues.
Enhanced monitoring: With health checks in place, we gain better visibility into the status of each service, facilitating proactive maintenance and troubleshooting.
Increased …
> feat: docker-compose healthz check

- server/model/system/request/sys_menu.go
- server/model/system/sys_authority_menu.go
- server/model/system/sys_base_menu.go
- server/plugin/plugin-tool/utils/check.go
- server/service/system/sys_authority.go
- server/service/system/sys_auto_code.go
- server/service/system/sys_menu.go
- server/source/system/menu.go
- web/src/view/superAdmin/menu/menu.vue
解决 #1700 
将ParentId 声明由 string 改成是 uint
理由：
1. 数据库的类似是bigint但代码中是string， 数据库可能运行但不能走索引（如果有）
2. 在代码中map使用uint做key更省内存和更快，可参考 https://stackoverflow.com/questions/72237864/string-vs-integer-as-map-key-for-memory-utilization-in-golang
缺点：
1. 不能向前兼容
2. 涉及修改文件多
> 多文件: 菜单parentId由string改成uint

- server/service/system/sys_export_template.go
修改原本循环的单条插入为批量插入，减少大量数据导入时的耗时，提高性能。
> sys_export_template.go: 导入Excel时使用批量插入提高性能

- server/service/system/sys_export_template.go
items切片初始化时指定了长度而非容量，而append从切片末尾开始追加，导致在将数据插入数据库时会出现空记录。
修改：
`items := make([]map[string]interface{}, len(values))` => `items := make([]map[string]interface{}, 0, len(values))`
> sys_export_template.go: 修复导入Excel时前几条为空数据的问题

- web/vitePlugin/codeServer/index.js
不支持路径有中文!!!!
目前在前端使用按键为 shift+alt +点击鼠标左键
说明: 只在开发环境中有用  需要将/web/.env.development中的VITE_POSITION改为open 
VITE_EDITOR设置为vscode或者websotrm即可开启使用,
> 点击跳转代码插件修复websotrm bug

- web/src/view/example/breakpoint/breakpoint.vue
复现步骤：
1.先选择一个文件
2.再次点击选择文件，点击取消  
3.控制台飘红且原文件被删除
> fixed: 修复文件分片上传在已选择文件的情况下，再次选择并取消出现控制台飘红且原文件清空的bug

- server/config.yaml
- server/config/config.go
- server/config/disk.go
- server/utils/server.go
- web/src/view/system/state.vue
默认为`/`，支持配置多路径，如下
Windows:
```
disk-list:
- mount-point: "C:"
- mount-point: "D:"
- mount-point: "E:"
```
Linux:
```
disk-list:
- mount-point: "/"
- mount-point: "/mnt/disk1"
- mount-point: "/mnt/disk2"
```
> 添加展示多硬盘用量信息的功能

- server/service/system/sys_export_template.go
- web/src/view/systemTools/exportTemplate/exportTemplate.vue
如果join时有两个表出现一样的字段就会造成其中一个字段显示为空，所以加了一个 as  给字段器一个别名优化完代码提交
> 优化如果join表时出现重复的字段或者需要有函数时可以导出别名的值

- web/src/pinia/modules/user.js
- web/src/view/login/index.vue
> style(login): 优化登陆部分代码，提升可读性

- server/model/system/sys_auto_code.go
- server/resource/autocode_template/web/table.vue.tpl
- web/src/view/systemTools/autoCode/component/fieldDialog.vue
给table.vue模板添加控制显示/隐藏更多查询条件的语句块和按钮，效果如下：
隐藏：
显示：
在代码生成器中可以直接控制默认的显隐状态，只有已经选择了查询条件的情况下才能编辑
> 添加通过点击展开/收起控制显示更多的查询条件的功能

- web/src/view/systemTools/system/system.vue
> Fixed system.vue: 日志留存时间json key错误

- server/resource/autocode_template/server/api.go.tpl
- server/resource/autocode_template/server/model.go.tpl
- server/resource/autocode_template/server/request.go.tpl
- server/resource/autocode_template/server/router.go.tpl
- server/resource/autocode_template/server/service.go.tpl
- server/resource/autocode_template/web/form.vue.tpl
- server/resource/autocode_template/web/table.vue.tpl
1. request.go.tpl and model.go.tpl indent problem
2. api.go.tpl, request.go.tpl, service.go.tpl struct {}
> Update: Template

- server/Dockerfile
在之前的版本中，存在一个工作路径切换的问题，这导致文件被错误地复制到根路径，而不是保持在预期的工作目录中。
为了支持使用sqlite数据库，添加了挂载目录的命令示例（默认注释掉）。
> Dockerfile修复工作路径的问题

- server/api/v1/system/sys_api.go
`GetApiGroups` 方法url路径为get，但swagger文档中为post
> feature:swagger 接口请求方式优化

- web/src/view/systemTools/autoCodeAdmin/index.vue
> fix: add funcName is sure UpperChar

- server/resource/plugin/server/model/model.go.template
> 修改模板，去除 `生成代码` model 行尾空格

- server/resource/package/web/view/table.vue.tpl
避免浏览器console的warn提示
Vue warn]: Invalid prop: type check failed for prop "column". Expected Number with value 1, got String with value "1".
> column参数类型是number

- server/api/v1/example/exa_file_upload_download.go
- server/api/v1/system/sys_user.go
- server/model/system/sys_user.go
- server/router/example/exa_file_upload_and_download.go
- server/router/system/sys_user.go
- server/service/example/exa_file_upload_download.go
- server/service/system/sys_user.go
- server/source/system/api.go
- server/source/system/casbin.go
- web/src/api/fileUploadAndDownload.js
- web/src/api/user.js
- web/src/components/upload/common.vue
- web/src/pinia/modules/app.js
- web/src/pinia/modules/user.js
- web/src/utils/format.js
- web/src/view/example/upload/upload.vue
- web/src/view/layout/setting/index.vue
- web/src/view/login/index.vue
- web/src/view/systemTools/system/system.vue
格式：文件名|链接或者仅链接；
示例：
我的图片|https://my-oss.com/my.png
https://my-oss.com/my_1.png
> 媒体库增加批量导入URL；将用户配置保存到数据库，刷新或者异地登录配置不丢失。

- web/src/core/global.js
- 支持插件资源图标
- 增强插件资源分离(插件的assets 资源放在插件目录(web)下即可)
- 可能还能帮助减少插件使用部署步骤(不用再拷贝到 assets 下了)，同时不影响老的部署使用方式(插件图标有插件名作为前缀)
> feat: edit global.js support plugin svg

- server/model/common/basetypes.go
新初始化数据库，修改前端配置后，把origin_setting当作[]byte去读取会报错：
```json
{"error": "sql: Scan error on column index 13, name \"origin_setting\": Scan source was not []bytes"}
```
如果数据库不支持json的话一般是当作text来存的吧，所以应该可以直接改成当string去读取（我只在pgsql下进行了测试）
> Update basetypes.go, fixed origin_setting column read error

- server/resource/package/server/service/service.go.tpl
- server/resource/plugin/server/service/service.go.template
生成的代码，统一使用 `// Author [yourname](https://github.com/yourname)` 作为 `Author` 。
本PR前:
```
/server/resource/function/server.go.tpl                      // 使用 `yourname` 作为 `Author`
/server/resource/package/server/service/service.go.tpl       // 使用 `piexlmax` 作为 `Author`
/server/resource/plugin/server/service/service.go.template   // 使用 `piexlmax` 作为 `Author`
```
本PR后:
```
/server/resource/function/server.go.tpl                      // 使用 `yourname` 作为 `Author`
/server/resource/package/server/service/service.go.tpl       // 使用 `yourname` 作为 `Author`
/server/resource/plugin/server/service/service.go.template   // 使用 `yourname` 作为 `Author`
```
> server: same Author "yourname" for gen Code

- web/src/core/global.js
- web/vite.config.js
修复插件目录下 svg 文件像 项目目录下的 svg 一样直接作为组件使用
> 插件目录下的 svg 文件会自动带插件名(目录名)前缀(防止不同插件目录下同 svg 文件名冲突问题)。
具体使用方法如下：
1. 在插件目录中任意目录结构下 存放 svg 文件。参考如下目录结构：
```bash
$ pwd
~/Projects/gin-vue-admin/web/src/plugin
$ tree email
email
├── api
│   └── email.js
├── assets
│   └── icons
│       └── ali
│           ├── c-coin-fill.svg
│           └── c-dataserver.svg
└── view
└── index.vue
```
2. 在开发模式下，浏览器 DevTool 控制台 console 中会列举出 所有扫描到可使用的 svg 组件使用代码。
3. 将 svg 组件代码复制后，直接在需要的地方即可在对应页面看到图表显示。如下代码所示：
> 一般推荐插件的 svg 仅在该插件内使用，以保持良好的代码和资源组织方式
```diff
diff --git a/web/src/plugin/email/view/index.vue b/web/src/plugin/email/view/index.vue
index 11d57e44..4b25ab58 100644
--- a/web/src/plugin/email/view/index.vue
+++ b/web/src/plugin/email/view/index.vue
@@ -1,6 +1,10 @@
<template>
<div>
<warning-bar …
```
> fix: support pluginPath svg file as component show list when dev mode

- server/resource/package/web/view/form.vue.tpl
- server/resource/package/web/view/table.vue.tpl
表单提交的时候按钮添加loading状态，防止手滑连点后重复创建
> 表单提交按钮增添loading，防连点

- web/src/view/superAdmin/menu/icon.vue
> web/src/view/superAdmin/menu/icon.vue: 后台菜单管理中选择图标时增加可选自定义图标

- web/src/utils/date.js
> 替换被弃用的RegExp.$1、substr

- web/src/view/systemTools/autoCode/index.vue
自动化代码时，点击使用此表。
问题一：
问题二：
因包名（form.value.packageName）是大写开头，导致生产代码是下划线开头，导致编译时报错。
> fixed:修复表名是大写字母开头时，自动化代码异常问题。

- .gitignore
- server/plugin/announcement/model/info.go
- server/service/system/sys_casbin.go
- server/utils/upload/minio_oss.go
- `.gitignore`: 忽略 Windows 下编译的二进制文件和 SQLite 数据文件
- 修复结构体 tag 字段的错误使用, 结构体的 tag 字段的多个 key-value 对需要使用空格分隔
- 处理返回的 cancel 函数, 避免 context 泄露
- 修复 `UpdateCasbinApi` 方法遗漏的错误处理
> 修复可能的 context 泄露以及遗漏的错误处理

- server/api/v1/system/sys_export_template.go
- server/resource/package/server/api/api.go.tpl
更新模板文件 `api.go.tpl` 中 `FindXxx` (即，用id查询Xxx) 接口，这会造成 swag init 提示，同时也符合接口描述
> [`swag`](https://github.com/swaggo/swag) 工具中，注释请求的 `query` 目前好像不用 ast 扫描对应结构体
> 生成模板中注释文档 query 修改

- server/resource/package/server/api/api.go.tpl
- server/resource/plugin/server/api/api.go.template
使用模板语法 `{{.PrimaryField.FieldJson}}` 替换
> 模板文件文档注释修改

- server/api/v1/system/sys_user.go
- server/utils/claims.go
- Refactor JWT token generation, use `New()` function instead of create instance directly.
- Improve error handling flow in `SetUserAuthority`, remove `else` block, to make the code more readable.
- Remove redundant `err != nil` judgment.
> Optimize JWT using `New()` instead of create instance directly

- server/middleware/jwt.go
- server/utils/breakpoint_continue.go
- server/utils/jwt.go
- server/utils/zip.go
- 使用 strings.Contains 替代 strings.Index 方法
- error 变量命名使用 `Err` 前缀修饰，且 error 信息为开头小写，具体参考 Go 官方规范 https://go.dev/wiki/CodeReviewComments#error-strings
This change improves code readability and follows better Go naming conventions for error variables.
> refactor: rename error with `Err` prefix to follow Go conventions

- web/src/components/commandMenu/index.vue
- web/src/pathInfo.json
- web/src/permission.js
- web/src/router/index.js
- web/src/view/dashboard/index.vue
- web/src/view/layout/aside/combinationMode.vue
- web/src/view/layout/aside/headMode.vue
- web/src/view/layout/aside/normalMode.vue
- web/src/view/layout/iframe.vue
- web/src/view/person/person.vue
fix: 添加内部 iframe 网页，需要将 name 设置成 Iframe
optimization：优化 permission.js 逻辑
> fix: 添加内部 iframe 展示网页，优化 permission.js 逻辑

- web/package.json
- web/src/components/selectImage/selectImage.vue
- web/src/components/upload/QR-code.vue
- web/src/components/upload/cropper.vue
- web/src/main.js
- web/src/permission.js
- web/src/router/index.js
- web/src/view/example/upload/scanUpload.vue
- web/src/view/example/upload/upload.vue
> 媒体库增加裁剪上传，扫码上传

- server/service/system/auto_code_package_test.go
- server/utils/captcha/redis.go
- web/package.json
- web/src/view/superAdmin/authority/components/menus.vue
- Add nil check for context parameter.
- UseWithCtx method returns explicit type rather than interface.
- Add missing `isPackage` argument called the test method.
> fix: check for nil and return explicit type for `UseWithCtx` method

- server/initialize/router.go
Fix the website icon request error due to missing `/favicon.ico` route.
> fix: register `favicon.ico` route as single file

- web/src/view/systemTools/autoPkg/autoPkg.vue
prevent autocode's package name don't conform to the naming rule of golang.
golang only apply [a-zA-z0-9_]
> fix: add new rule to verify package name

- server/core/viper.go
- Extract config path logic to separate `getConfigPath()` function.
- Simplify config priority handling: cmd flag > env variable > default by mode.
- Remove unnecessary param `path` for `viper()` function.
- Add fallback to default config path when mode-specific config file doesn't exist.
> refactor: separate config path acquisition to `getConfigPath()` function

- server/service/system/sys_export_template.go
- web/index.html
(1)Fix function ImportExcel for generating SQL correctly: Check excel title, remove the leading and trailing white spaces, skip the extra fields.修复表格标题行首尾空不匹配或多余的标题导致的SQL语句错误问题：去掉表格标题首尾空字符，并跳过多余的字段
(2)Fix icon path in the file index.html. 修复build之后icon路径问题
> sys_export_template.go: Fix function ImportExcel for generating SQL correctly

- server/go.mod
- server/go.sum
- server/service/system/auto_code_plugin.go
update deprecated lib mholt/archiver/v4 to mholt/archives
> auto_code_plugin.go: update deprecated lib mholt/archiver/v4 to mholt/archives

- server/utils/autocode/template_funcs.go
富文本中原有搜索条件为 `if %s && *info.%s != ""` 与创建的struct类型不匹配
> fix: 修复代码生成中时间和富文本的搜索错误

- web/src/components/richtext/rich-edit.vue
> fix: #2030 富文本编辑器全屏时部分内容会被其他表单项遮挡

- server/resource/package/server/service/service.go.tpl
在多库模式下生成代码时 选择关联模型时候如果选默认库如图
传的参数如下
生成的代码问题部分
**一个字段用了gva默认库 但是生成的代码两个都是用的业务库**
下面是定位的问题修改bug
> fix: 修复在多库模式下生成代码时候用默认库用错的情况

- server/config/email.go
- server/initialize/plugin_biz_v1.go
- server/plugin/email/README.MD
- server/plugin/email/config/email.go
- server/plugin/email/main.go
- server/plugin/email/utils/email.go
- web/src/view/systemTools/system/system.vue
IBM、微软等部分邮箱服务不支持标准库中的PlainAuth认证，仅支持LoginAuth认证，增加配置项
> 新增支持LoginAuth认证方式适用于IBM、微软等部分邮箱服务

- server/service/system/sys_authority.go
修复了在数据库状态异常时，角色权限管理页面相关接口调用GetParentAuthorityID会发生panic的问题
> sys_authority.go: Fix a potential nil pointer dereference in GetParentAuthorityID

- web/src/view/systemTools/autoCode/index.vue
> fix: 修复不小心选择业务库后想删掉的问题

- web/src/utils/request.js
服务端以 c.File 返回响应数据时，Response 没有 code 字段，会导致页面触发错误弹窗信息：undefined
> Fix Server 返回非 JSON 响应数据时导致错误弹窗

- web/src/view/systemTools/autoCode/index.vue
这里判断错了，应该是json类型的字段才禁用查询，而不是非json就禁用
> fix:修复查询条件无法添加问题

- server/api/v1/system/sys_user.go
- server/service/system/sys_user.go
- Simplify `ChangePassword` method signature by removing unnecessary return type.
- Use `Select()` to fetch only the necessary fields (`id` and `password`) from the database.
- Replace `Save()` with `Update()` for more efficient password update operation.
Note: use `Save(&user)` to update the whole user record, which will cover other unchanged fields as well, causing data inconsistency when data race conditions.
使用 update 替换 save，同时只更新要更新的字段，避免数据竞争时全覆盖造成数据错误。
> optimize: select and update necessary fields in `ChangePassword` method

- server/api/v1/system/sys_user.go
- server/utils/verify.go
Remove `CaptchaId` and `Captcha` fields from `LoginVerify` validation, and move captcha validation logic to the login handler.
Fix captcha validation issue when `OpenCaptcha` option is disabled.
refer #2063
> Fix captcha validation issue when `OpenCaptcha` option is disabled

- server/config.yaml
- server/config/system.go
- server/initialize/gorm.go
增加自动迁移autoMigrate开关配置
生产环境可以禁止自动迁移,使用更安全的手动确认
开发环境在数据库没有变动的情况下禁止自动迁移也可以加速启动
> feat: add autoMigrate config
